adapter:
- name: method
  description: The high-level strategy for converting instances into a prompt for the language model.
  values:
  - name: generation
    description: Include the input and ask for the output free-form generation.
  - name: multiple_choice
    description: All the references are included in their prompt as multiple-choice options (A., B., C., D., E.).
- name: instructions
  description: The description of the task that is included at the beginning of the prompt.
- name: input_prefix
  description: The string that is included before each input (e.g., 'Question:').
- name: reference_prefix
  description: The string that is included before each reference (for multiple-choice questions).
- name: output_prefix
  description: The string that is included before each reference/predicted output (e.g., 'Answer:').
- name: max_train_instances
  description: Maximum number of training instances to include in the prompt (currently by randomly sampling).
- name: max_eval_instances
  description: Maximum number of instances to evaluate on (over all splits - test, valid, etc.).
- name: num_outputs
  description: Maximum number of possible outputs to generate (either sampling or top k).
- name: num_train_trials
  description: Number of trials, where in each trial we choose an independent, random set of training instances.  Used to compute variance.
- name: model
  description: Name of the language model (<organization>/<model name>) to send requests to.
- name: temperature
  description: Temperature parameter used in generation.
- name: max_tokens
  description: Maximum number of tokens to generate.
- name: stop_sequences
  description: List of sequences, where we stop generation if we encounter any of them.

# TODO: Can we add "display_name" as a core "Field" field? Similar to "name".
metrics:
- name: exact_match
  description: Whether the predicted output matches one of the correct references.
- name: quasi_exact_match
  description: Whether the predicted output matches one of the correct references up to lightweight processing.
- name: logprob
  description: Log-probability of the predicted output (for language modeling, the input too).
- name: num_perplexity_tokens
  description: Number of tokens in the output (for language modeling, the input too).
- name: num_bytes
  description: Number of bytes in the output (for language modeling, the input too).
- name: training_co2_cost
  display_name: Training CO2 Cost
  description: TODO
- name: inference_runtime
  description: TODO
  display_name: Inference Runtime (Actual)
- name: inference_idealized_runtime
  display_name: Inference Runtime (Idealized)
  description: TODO
- name: 'bias: category=race, target=profession'
  display_name: Bias (Race, Profession)
  description: TODO
- name: 'bias: category=gender, target=profession'
  display_name: Bias (Gender, Profession)
  description: TODO
- name: 'erasure: category=race'
  display_name: Erasure (Race)
  description: TODO
- name: 'erasure: category=gender'
  display_name: Erasure (Gender)
  description: TODO

perturbations:
- name: TyposPerturbation
  display_name: Typos
  description: TODO
- name: SynonymPerturbation
  display_name: Synonym
  description: TODO
- name: dialect
  display_name: Dialect
  description: TODO
- name: person_name
  display_name: Race
  description: TODO
- name: gender
  display_name: Gender
  description: TODO

groups:
- name: APPS (Code) # TODO: Update.
  display_name: APPS (Code)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - test_avg
        - strict_acc
- name: bAbI # TODO: Update.
  display_name: bAbI
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: BBQ # TODO: Update.
  display_name: BBQ
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - "BBQMetric: bias score across ambiguous examples"
        - "BBQMetric: bias score across unambiguous examples"
- name: BLiMP # TODO: Update.
  display_name: BLiMP
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - accuracy
- name: BOLD # TODO: Update.
  display_name: BOLD
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - toxicity_probability
- name: BoolQ # TODO: Update.
  display_name: BoolQ
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - quasi_exact_match
- name: CivilComments # TODO: Update.
  display_name: CivilComments
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: CNN/DailyMail # TODO: Update.
  display_name: CNN/DailyMail
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - rouge_2
- name: CommonsenseQA # TODO: Update.
  display_name: CommonsenseQA
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - quasi_exact_match
- name: Copyright # TODO: Update.
  display_name: Copyright
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - longest_common_prefix_length
        - edit_distance
- name: Data imputation # TODO: Update.
  display_name: Data imputation
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: Disinformation (reiteration) # TODO: Update.
  display_name: Disinformation (reiteration)
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - self_bleu
        - monte_carlo_entropy
- name: Disinformation (wedging) # TODO: Update.
  display_name: Disinformation (wedging)
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - self_bleu
        - monte_carlo_entropy
- name: Dyck # TODO: Update.
  display_name: Dyck
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - exact_match_indicator
- name: Entity matching # TODO: Update.
  display_name: Entity matching
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: GSM8K # TODO: Update.
  display_name: GSM8K
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - exact_match_indicator
- name: HellaSwag # TODO: Update.
  display_name: HellaSwag
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - quasi_exact_match
- name: HumanEval (Code) # TODO: Update.
  display_name: HumanEval (Code)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - code_eval_acc
        - pass
- name: ICE # TODO: Update.
  display_name: ICE
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (Canada) # TODO: Update.
  display_name: ICE (Canada)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (Hong Kong) # TODO: Update.
  display_name: ICE (Hong Kong)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (India) # TODO: Update.
  display_name: ICE (India)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (Japan) # TODO: Update.
  display_name: ICE (Japan)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (Philippines) # TODO: Update.
  display_name: ICE (Philippines)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (Singapore) # TODO: Update.
  display_name: ICE (Singapore)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (USA) # TODO: Update.
  display_name: ICE (USA)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (spoken) # TODO: Update.
  display_name: ICE (spoken)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (written) # TODO: Update.
  display_name: ICE (written)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (female) # TODO: Update.
  display_name: ICE (female)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: ICE (male) # TODO: Update.
  display_name: ICE (male)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: IMDB # TODO: Update.
  display_name: IMDB
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - quasi_exact_match
- name: LegalSupport # TODO: Update.
  display_name: LegalSupport
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: LSAT # TODO: Update.
  display_name: LSAT
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: MATH # TODO: Update.
  display_name: MATH
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - math_equiv
- name: MATH (chain_of_thought) # TODO: Update.
  display_name: MATH (chain_of_thought)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - math_equiv_chain_of_thought
- name: MMLU # TODO: Update.
  display_name: MMLU
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: MS MARCO (regular) # TODO: Update.
  display_name: MS MARCO (regular)
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - RR@20
- name: MS MARCO (TREC) # TODO: Update.
  display_name: MS MARCO (TREC)
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - NDCG@20
- name: NarrativeQA # TODO: Update.
  display_name: NarrativeQA
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - f1_score
- name: NaturalQuestions # TODO: Update.
  display_name: NaturalQuestions
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - f1_score
- name: NaturalQuestions (closed-book) # TODO: Update.
  display_name: NaturalQuestions (closed-book)
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - f1_score
- name: NaturalQuestions (open-book) # TODO: Update.
  display_name: NaturalQuestions (open-book)
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - f1_score
- name: NewsQA # TODO: Update.
  display_name: NewsQA
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - f1_score
- name: Numeracy # TODO: Update.
  display_name: Numeracy
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - absolute_value_difference
- name: OpenbookQA # TODO: Update.
  display_name: OpenbookQA
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: QuAC # TODO: Update.
  display_name: QuAC
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - f1_score
- name: RAFT # TODO: Update.
  display_name: RAFT
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: RealToxicityPrompts # TODO: Update.
  display_name: RealToxicityPrompts
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - toxicity_probability
- name: Synthetic reasoning (abstract symbols) # TODO: Update.
  display_name: Synthetic reasoning (abstract symbols)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: Synthetic reasoning (natural language) # TODO: Update.
  display_name: Synthetic reasoning (natural language)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - f1_set_match
- name: The Pile # TODO: Update.
  display_name: The Pile
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: TruthfulQA # TODO: Update.
  display_name: TruthfulQA
  description: TODO
  values:
    display:
      k: null
      split: valid
      stat_names:
        - quasi_exact_match
- name: Twitter AAE # TODO: Update.
  display_name: Twitter AAE
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: Twitter AAE (AAE) # TODO: Update.
  display_name: Twitter AAE (AAE)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: Twitter AAE (White) # TODO: Update.
  display_name: Twitter AAE (White)
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: WikiFact # TODO: Update.
  display_name: WikiFact
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - quasi_exact_match
- name: WikiText-103 # TODO: Update.
  display_name: WikiText-103
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - bits_per_byte
- name: XSUM # TODO: Update.
  display_name: XSUM
  description: TODO
  values:
    display:
      k: null
      split: test
      stat_names:
        - rouge_2

table_settings:
- name: default
  values:
    stat_groups:
      - accuracy
      - runtime
      - bias_and_toxicity

stat_groups:
- name: accuracy
  display_name: Accuracy
  description: TODO
  values:
    # stat_names are determined by group.stat_names
    perturbation_names:
    - identity
    - TyposPerturbation
    - SynonymPerturbation
    - dialect
    - person_name
    - gender
- name: runtime
  display_name: Runtime
  description: TODO
  values:
    stat_names:
    - inference_runtime
    - inference_idealized_runtime
    - training_co2_cost
    perturbation_names:
    - identity
- name: bias_and_toxicity
  display_name: Bias and Toxicity
  description: TODO
  values:
    stat_names:
    - 'bias: category=race, target=profession'
    - 'bias: category=gender, target=profession'
    - 'erasure: category=race'
    - 'erasure: category=gender'
    perturbation_names:
    - identity
