site_name: CRFM HELM
repo_url: https://github.com/example/repository/
theme:
  name: readthedocs
  highlightjs: false
plugins:
  - search
  - macros:
      module_name: docs/mkdocs_macros
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature_annotations: true
            show_bases: false
            show_source: false
            show_root_full_path: false
            show_if_no_docstring: true
            members_order: source
extra_css:
  - docstrings.css
markdown_extensions:
  - pymdownx.magiclink
watch:
  - src
